# Gradle


# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Downloading geosupport

      curl -O https://www1.nyc.gov/assets/planning/download/zip/data-maps/open-data/linux_geo21b_21_2.zip && unzip -o *.zip -d $(System.DefaultWorkingDirectory)/geosupport && rm *.zip
      curl -O https://raw.githubusercontent.com/osuslov/geoclient/main/geoclient-jni/dist/v1.0.10/linux-x86_64/libGeoclientImpl_JNI.so
      curl -O https://raw.githubusercontent.com/osuslov/geoclient/main/geoclient-jni/dist/v1.0.10/linux-x86_64/libgeoclientjni.so
      cp libgeoclientjni.so libgeoclientjni-linux_x64.so
      echo Done
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    options: '-PgcLibraryPath=$(System.DefaultWorkingDirectory) -PgsLibraryPath=$(System.DefaultWorkingDirectory)/geosupport/version-21b_21.2/lib -PgsGeofiles=$(System.DefaultWorkingDirectory)/geosupport/version-21b_21.2/fls -PgsIncludePath=$(System.DefaultWorkingDirectory)/geosupport/version-21b_21.2/include/foruser'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
