# Gradle


# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Downloading geosupport

      curl -O https://www1.nyc.gov/assets/planning/download/zip/data-maps/open-data/linux_geo21b_21_2.zip && unzip -o *.zip -d $(System.DefaultWorkingDirectory)/geosupport && rm *.zip
      
      export GS_LIBRARY_PATH=$(System.DefaultWorkingDirectory)/geosupport/version-21b_21.2/lib
      export GEOFILES=$(System.DefaultWorkingDirectory)/geosupport/version-21b_21.2/fls
      export GS_INCLUDE_PATH=$(System.DefaultWorkingDirectory)/geosupport/version-21b_21.2/include/foruser
      echo Done
      find . -name libgeoclientjni.so
    workingDirectory: '$(System.DefaultWorkingDirectory)'


